name: "shop-bot"

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: default_db
      POSTGRES_USER: officer
      POSTGRES_PASSWORD: officer-password
    ports:
      - 5432:5432

  redis:
    image: redis/redis-stack
    container_name: redis
    restart: always
    ports:
      - 6379:6379

  redisinsight:
    image: redis/redisinsight
    container_name: redisinsight
    restart: always
    ports:
      - 5540:5540
